### ISSUE TITLE
Menu Section

### ISSUE THREAD

**Issue by cyouh95** [Cr4ck3r/teecoozy#2]
Don't forget to add the width property of this section according to the spec. Also, instead of setting a specific value for the margin, change it to `auto` so that it will automatically adjust the margins according to the width of the browser (and in this case, properly center this section):

```css
.menu {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;

  text-align: center;

  height: 600px;
  width: 1000px;
  margin: auto;
  padding-top: 0px;

  padding-bottom: 0px;
}
```

https://github.com/Cr4ck3r/teecoozy/blob/master/index.html#L39-L61
https://github.com/Cr4ck3r/teecoozy/blob/master/resources/css/style.css#L74-L87
